builds:
- env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    homepage:  https://github.com/globocom/slo-generator
    description: Easy setup a service level objectives using prometheus
    maintainer: Wilson Júnior <wilson.junior@corp.globo.com>
    license: MIT
    vendor: Globo.com
    formats:
    - deb
    - rpm
