{
 "title": "Globo.com SLIs/SLOs -  Long Term",
 "tags": [
  "sli",
  "slo",
  "long-term"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "window", "label": "Window", "query": "1h,1d,5m" },
   {
    "name": "platform",
    "label": "Platform",
    "query": "label_values(slo:service_errors_total:ratio_rate_1h, platform)"
   },
   {
    "name": "services",
    "query": "label_values(slo:service_traffic:ratio_rate_1h{platform=~\"$platform\"}, service)"
   }
  ]
 },
 "panels": [
  { "title": "SLIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(slo:service_traffic:ratio_rate_$window{service=~\"$services\", platform=~\"$platform\"}) by (service)",
     "legendFormat": "{{ service }}"
    }
   ]
  },
  {
   "title": "Errors - %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "sum(slo:service_errors_total:ratio_rate_$window{service=~\"$services\", platform=~\"$platform\"}) by (service)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ service }}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(slo:service_latency:p50_$window{service=~\"$services\", platform=~\"$platform\"}) by (service)",
     "legendFormat": "{{ service }} - median"
    },
    {
     "expr": "sum(slo:service_latency:p95_$window{service=~\"$services\", platform=~\"$platform\"}) by (service)",
     "legendFormat": "{{ service }} - p95"
    },
    {
     "expr": "sum(slo:service_latency:p99_$window{service=~\"$services\", platform=~\"$platform\"}) by (service)",
     "legendFormat": "{{ service }} - p99"
    }
   ]
  },
  { "title": "SLOs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Alerts",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short", "label": "alerts" }
   ],
   "targets": [
    {
     "expr": "count(ALERTS{severity=\"page\", service=~\"$services\", platform=~\"$platform\"}) by (service, alertname)",
     "legendFormat": "{{ service }} - {{ alertname }} - page"
    },
    {
     "expr": "count(ALERTS{severity=\"ticket\", service=~\"$services\", platform=~\"$platform\"}) by (service, alertname)",
     "legendFormat": "{{ service }} - {{ alertname }} - ticket"
    }
   ]
  },
  {
   "title": "Availability",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "1-sum(slo:service_errors_total:ratio_rate_$window{service=~\"$services\", platform=~\"$platform\"}) by (service)",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "{{ service }}",
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(slo:service_latency:ratio_rate_$window{service=~\"$services\", platform=~\"$platform\"}) by (service, le)",
     "legendFormat": "{{ service }} < {{ le }}s"
    }
   ]
  }
 ]
}